server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://album-db:5432/albumdb
    username: album
    password: album
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always
